### ISSUE TITLE
add credits for contributors outside of SF

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/measuringoutcome-es#4]
In the readme.md for sure, maybe also find a place in the card deck/ppt

**Comment by sjoerdly** [comment]
Se that this is still in the verify column. 

I have just added the translator @natastro to the PPT file. Can you confirm that this is proper Spanish Natalie? Before I make the new release I don't want to spoil the proper other translations with a bad google translate... ;)

![image](https://user-images.githubusercontent.com/1508446/103273227-0e27c280-49bf-11eb-9ffc-b0412a330cfa.png)

**Comment by natastro** [comment]
Hi @sjoerdly ! I have gone back through that slide and revised a few places to improve translation. Happy New Year! 🎉

**Comment by sjoerdly** [comment]
Thanks @natastro I will try to create a new pdf and release asap. 

Happy new year!

**Comment by sjoerdly** [comment]
Hi Natalie, I fear something went wrong saving/committing. the new PPT has the english title card again (instead of english) and the only thing I see changed is a revert of my own changes in the bottom right part.

See https://www.diffchecker.com/FR8Ek89j (left my last commit, right your commit)

I hope you have the changes you made somewhere still, for now I will revert your changes as they undid my last commit and the spanish title.

If you want to redo your changes, please do so, and let me know when it's ready. Appreciate your help a lot!

**Comment by natastro** [comment]
Hi @sjoerdly ! Let me know if the newest upload worked 😊 I do want to note: some words in the slide will have English use and that's for things like names or titles. Names or titles stick to what they already are and do not receive a translation. For example: since Scrum Facilitators is an organization/group, it will stay that way. But, if someone has the role of being a scrum facilitator, they are known as a facilitador de Scrum (Scrum not being translated because it's another name/title)

Hope this helps! Please let me know if you need anything!

**Comment by sjoerdly** [comment]
It seems like it worked. thanks for reupping @natastro and your short explanation of some of the changes.

For reference on those changes: https://www.diffchecker.com/nJPPI7E0

This looks good and I will make the PDF and release for 1.1 later today. :-)

**Comment by natastro** [comment]
Thanks @sjoerdly ! 😀 I just got up and saw the post on LinkedIn, thank you! I can go ahead and update Jugo > Juego for you as well, my apologies!

**Comment by sjoerdly** [comment]
No problem already fixed. This is something even I can do ;-)
